GET http://localhost:8080/hello

###

POST http://localhost:8080/api/auth/signup HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2QiLCJpYXQiOjE3MDE1NTc2NTAsImV4cCI6MTcwMTY0NDA1MH0.qaoOpnUqSj9SoywfFxpdyIYl_O-ocuofRu5R4JOcwsg
content-type: application/json

{
    "username": "mod",
    "email": "mcollin4@citadel.edu",
    "password": "12345678",
    "role": ["mod"]
}

###
GET http://localhost:8080/api/test/all

###

POST http://localhost:8080/api/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "mod",
    "password": "12345678"
}

###
GET http://localhost:8080/api/test/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2QiLCJpYXQiOjE3MDE1NTc2NTAsImV4cCI6MTcwMTY0NDA1MH0.qaoOpnUqSj9SoywfFxpdyIYl_O-ocuofRu5R4JOcwsg

 
###
GET http://localhost:8080/api/test/mod
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2QiLCJpYXQiOjE3MDEzMDQ2NzgsImV4cCI6MTcwMTM5MTA3OH0.s5jiHoClBbObGyq_vHTvqzPhfnmIb3rGMivsjTLtV0c

###
GET http://localhost:8080/api/test/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb2QiLCJpYXQiOjE3MDEzMDIzNTIsImV4cCI6MTcwMTM4ODc1Mn0.TgN-4eaNLRr94cR5ZBYTE6yXZ6Z_PlFiFynmYl7M38Q

