apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment2flaskdb
  namespace: assignment2  # specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment2flaskdb
  template:
    metadata:
      labels:
        app: assignment2flaskdb
    spec:
      containers:
      - name: assignment2flaskdb
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306

