GET http://localhost:8080/hello

###

POST http://localhost:8080/ HTTP/1.1
content-type: application/json

{
    "id": "foo",
    "name": "Mr. Foo",
    "phone": "123-123-1234"
}

###

GET http://localhost:8080/foo

###

GET http://localhost:8080/v2/api-docs

###

GET http://localhost:8080/writeToRedis?key=ab12&value=Hello%20World04

###

GET http://localhost:8080/writeToRedis?key=ab13&value=Hello%20World04

###

GET http://localhost:8080/writeToRedis?key=ab14&value=Hello%20World04

###

GET http://localhost:8080/writeToRedis?key=ab16&value=Hello%20World04

