apiVersion: v1
kind: Service
metadata:
  name: voteapp-lb-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080  # Specify the node port you want to expose
    protocol: TCP
  selector:
    app: voteapp-lb
