apiVersion: v1
kind: Service
metadata:
  name: voteapp-redis-service
  namespace: voteapp
spec:
  selector:
    app: voteapp-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
