apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-worker
  namespace: voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voteapp-worker
  template:
    metadata:
      labels:
        app: voteapp-worker
    spec:
      containers:
      - name: voteapp-worker
        image: matthewcollinsece/vote-app-worker
        ports:
        - containerPort: 8081
