apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-redis
  namespace: voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voteapp-redis
  template:
    metadata:
      labels:
        app: voteapp-redis
    spec:
      containers:
      - name: voteapp-redis
        image: matthewcollinsece/voteapp-redis
        ports:
        - containerPort: 6379
