apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp-user-fe
  namespace: voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voteapp-user-fe
  template:
    metadata:
      labels:
        app: voteapp-user-fe
    spec:
      containers:
      - name: voteapp-user-fe
        image: matthewcollinsece/voteapp-user-front-end
        ports:
        - containerPort: 81
