version: '3'

services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password  
    ports:
      - "3306:3306"
    networks:
      - assignment2FlaskNetwork
    container_name: assignment2FlaskDB
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    

  init:
    image: assignment2sqlinit:latest
    networks:
      - assignment2FlaskNetwork
    depends_on:
      db:
        condition: service_healthy
    container_name: assignment2SQLInit

  
  web:
    image: assignment2flaskapp:latest
    ports:
      - "8081:8081"
    networks:
      - assignment2FlaskNetwork
    depends_on:
      - db
      - init
    container_name: assignment2FlaskApp

networks:
  assignment2FlaskNetwork:
